### ISSUE TITLE
[v10xx] Reorganize the database

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/KODatabase#1]
## Description

It is of great importance to separate the connections and the processed data by dividing the database into parts. This will require separate efforts for each database in case of potential problems or security vulnerabilities and will prevent easy access to all data. Along with these, authorizations and access permissions can be easily formatted, and some databases will be used only for server access. 

Thus, when an external connection is required, it will not be able to access all the data, but only view and edit the data in the database that needs to be processed. In addition, additional plans are made regarding this database separation within the server files.

### **Rules**
- All database names must be named with the `UpperFlatCase` rule.
- All database users must be named with the `UpperFlatCase` rule.

## Tasks

1. The database will be divided into four separate parts.

   - [x] **OPENKO_ACCOUNT** (Database to store website, store and general account information)
   - [x] **OPENKO_COMMON** (Database to store general game data)
   - [x] **OPENKO_SERVER** (Database where data about the game server will be stored)
   - [x] **OPENKO_LOG** (Database where all log records will be stored)

2. Import and export scripts will be created with powershell for databases.

   - [x] **OPENKO_ACCOUNT** (It will auto-generate with import and export scripts)
   - [x] **OPENKO_COMMON** (It will auto-generate with import and export scripts)
   - [x] **OPENKO_SERVER** (It will auto-generate with import and export scripts)
   - [x] **OPENKO_LOG** (It will auto-generate with import and export scripts)

3. Separate users will be created for the databases.

   - [x] **OPENKO_ACCOUNT_USER** (It will be created automatically with the powershell script)
   - [x] **OPENKO_COMMON_USER** (It will be created automatically with the powershell script)
   - [x] **OPENKO_SERVER_USER** (It will be created automatically with the powershell script)
   - [x] **OPENKO_LOG_USER** (It will be created automatically with the powershell script)

**Comment by selcukcukur** [comment]
Related commits : https://github.com/selcukcukur/KODatabase/commit/25d032240f3b6c82c05d48b79d92b2b9faee3ff9 - https://github.com/selcukcukur/KODatabase/commit/b02ccf3e797d6c96af2c3fab1079751263def6a2
