### ISSUE TITLE
[v10xx] Reorganize the database tables

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/KODatabase#2]
## Description

Database tables should be reorganized and activities such as column naming and table naming should be shaped in accordance with certain standards. Projects without certain standards are doomed to chaos and confusion. This is a process we do not want. It will be reorganized according to the determined basic standards.

These processes are important in terms of the readability of the project and its development for everyone. While reorganizing database tables, errors in data types should be taken into account and should be organized by targeting modern techniques.

### **Rules**
- All table and column names must be named with the `UpperFlatCase` rule.
- All table names must be named with the `UpperFlatCase` rule.
- All table columns must be named with the `PascalCase` rule.

## Tasks

- [ ] Rebuild the database tables.
- [ ] Rearrange the columns of the database tables.
- [ ] Auto-generate database tables with powershell script.
